### ISSUE TITLE
Add a spike:run command to gulp.

### ISSUE THREAD

**Issue by ariporad** [emiw/redstone-dispatcher#1]
It should run the spike with the name passed in.

Also, we could have a spike:create command. (It might be a little better placed in a generator though. plus, it's really not that hard to create a spike, its a folder and a single file.)

**Comment by ariporad** [comment]
After some further investigation, I've determined that there's no good way to do this via gulp. If it becomes a big issue, I'll figure something out.

**Comment by ZoeLe** [comment]
ok
